const HOUR_FORMAT_OPTIONS = ['12 hour', '24 hour'];
const DAY_FORMAT_OPTIONS = ['Short (Mon)', 'Long (Monday)', "Don't show day"];
const MONTH_FORMAT_OPTIONS = ['Short (Jan)', 'Long (January)'];
const YEAR_FORMAT_OPTIONS = ['Short (23)', 'Long (2023)', "Don't show year"];

// introduction
const DEFAULT_ENABLE_INTRODUCTION = true;
const DEFAULT_ENABLE_GREETING = false;

// time
const DEFAULT_ENABLE_TIME = true;
const DEFAULT_SHOW_SECONDS = false;
const DEFAULT_HOUR_FORMAT = HOUR_FORMAT_OPTIONS[0];

// date
const DEFAULT_ENABLE_DATE = true;
const DEFAULT_DAY_FORMAT = DAY_FORMAT_OPTIONS[0];
const DEFAULT_MONTH_FORMAT = MONTH_FORMAT_OPTIONS[0];
const DEFAULT_YEAR_FORMAT = YEAR_FORMAT_OPTIONS[1];

// search
const DEFAULT_ENABLE_SEARCH = true;

// rows
const DEFAULT_ROWS: string[] = [];

export { HOUR_FORMAT_OPTIONS, DAY_FORMAT_OPTIONS, MONTH_FORMAT_OPTIONS, YEAR_FORMAT_OPTIONS };
export {
	DEFAULT_ENABLE_INTRODUCTION,
	DEFAULT_ENABLE_GREETING,
	DEFAULT_ENABLE_TIME,
	DEFAULT_SHOW_SECONDS,
	DEFAULT_HOUR_FORMAT,
	DEFAULT_ENABLE_DATE,
	DEFAULT_DAY_FORMAT,
	DEFAULT_MONTH_FORMAT,
	DEFAULT_YEAR_FORMAT,
	DEFAULT_ENABLE_SEARCH,
	DEFAULT_ROWS
};
